### ISSUE TITLE
Bungee Kicks, Mutes & Warnings

### ISSUE THREAD

**Issue by Haidyn** [confuser/Ban-Management#113]
I'm using BanManager on a BungeeCord network with 2 servers linked together.
Permanent bans & temporary bans work perfectly, you can ban and unban users even if they're on a different server to you, I'm guessing these commands don't check if the user is online which is why it works.

Would it be possible to have the same implemented for kicks, warnings and mutes so they will work through both of my servers too?

Thanks

**Comment by confuser** [comment]
/*all commands added in latest developer build
