### ISSUE TITLE
Error upon warning someone

### ISSUE THREAD

**Issue by DrkProdigy69** [confuser/Ban-Management#127]
Upon warning someone we get this error every time.
http://hastebin.com/ahasicunih.avrasm

**Comment by confuser** [comment]
Can you post a copy of your config? Make sure to remove your database details.

**Comment by DrkProdigy69** [comment]
http://hastebin.com/udibugafex.sm
Also, we've been wanting to remove the IP's that show up when we do /bminfo because we're wanting to give the command to lower staff ranks, but we don't want them having ip access. Anyway to do that?

**Comment by FourDown** [comment]
We are also interested in being able to control what is displayed in /bminfo.

**Comment by confuser** [comment]
I'm currently refactoring Message so nested keys can be used, which will make what you've asked much easier. However this is digressing from this issue.


Which developer build are you using that throws the error you are seeing on /warn ?

**Comment by DrkProdigy69** [comment]
I'm pretty sure we're running version v5.0.0-SNAPSHOT

**Comment by confuser** [comment]
http://ci.frostcast.net/job/BanManager/

Which build number?

**Comment by DrkProdigy69** [comment]
Build #30
