### ISSUE TITLE
plugin enchantment 

### ISSUE THREAD

**Issue by theshadyonehd** [confuser/Ban-Management#129]
Hey, I have issues with players with multiple accounts and multiple ips.

the enchantment would track all ips and all players whom join with any of the ips so for example:

**for the example i used names but the names will be the users UUID's

Theshadyonehd ip: 1.1.1.1
Theshadyonehd Ip: 1.1.1.1
Epic_ninja ip: 1.1.1.1
Theshadyonehd Ip: 1.1.1.2
shadyone ip 1.1.1.2
shadyone ip: 1.1.1.3
thisenchantment ip 1.1.1.3

Say we want to ban thisenchantment. we write (/banall thisenchantment hacking). this would ban all the above names and ips because they are linked in one way or another, by ip or UUID. then after the ban the plugin will scan the ips and UUID's to further ban other ip's and UUIDs linked to the players original account.

**Comment by confuser** [comment]
The ip addresses you've listed in your example are all different. I presume you mean to ban an entire ip range? If so, that's not a great idea as you'd more than likely end up accidentally banning players that are not associated with the person you are banning.

Also /banall is already used by the external banning system. Any suggestions as to a different command name?

**Comment by theshadyonehd** [comment]
no that is not what i mean at all.

See how "thisenchantment" has the same ip as shadyone? that would mean that this is the same player and both should be banned

but see how "shadyone" also used ip "1.1.1.2" ? that means the player "shadyone" is linked to any players using this ip therefore "shadyone is linked to "theshadyonehd".

Therefore "thisenchantment" is linked to "theshadyonehd" meaning they should both ban banned and the ips they used.

if you understand you can see how the player "thisenchantment" is actually the same player as "theshadyonehd" just using different ips and/or names...

understand?

**Comment by confuser** [comment]
Effectively an ip history for players.

I can see this being useful, however, v5 has not been built for such a feature, plus keeping a database of every player's ip address can in some countries be illegal.

Closing for now, will re-visit at a later date, perhaps BanManager v6.

**Comment by theshadyonehd** [comment]
It is also a history of other usernames used with that ip. Players are either making new accounts, changing ips or both to get around the banning. I would like to see this feature added because it is really hard keeping out some players. I have had players with 10+ accounts just change their ip and come straight back. Now this would not completely defeat the problem, just make it harder for them.
