### ISSUE TITLE
Conversion issues with IPs

### ISSUE THREAD

**Issue by CurePindal** [confuser/Ban-Management#133]
Hello!

Ive tried build 33 to convert my tables from BanManager v1.64. (Yes, way back but it worked without issues, so "never change a running system")
We havent logged player IPs and after the conversion the new players-table has "21307xxxxx" entered as IP for all players. I have no clue where that number comes from or if its a default? 

Anyway, it seems there needs to be a value for "no IP logged", because this way it messes up all player lookups by showing all of this converted users as possible alt accounts (same ip)!

Anyway to fix this?

**Comment by confuser** [comment]
It defaults to 127.0.0.1 if no ip address is found. The solution to this is to add 127.0.0.1 to bypassDuplicateChecks

https://github.com/confuser/Ban-Management/blob/master/src/main/resources/config.yml#L69-L70

**Comment by CurePindal** [comment]
Cant agree from what I see in my table. The number entered as IP is "2130706433" - no clue where that comes from.
And also, if you use 127.0.0.1 as default, wouldnt it also mess up the lookup of such users, because it will show them as associated by IP?

**Comment by confuser** [comment]
The ip address is stored as a long, the number you have quoted is 127.0.0.1 in human readable form. It's not stored as a string i.e. x.x.x.x for performance and efficiency reasons.

Yes it will, but there's nothing else that can be stored. IP storage is no longer optional.

**Comment by frdmn** [comment]
@CurePindal To quickly convert between long and IP format without the need of writing code:

http://long2ip.onlinephpfunctions.com/ as well as http://ip2long.onlinephpfunctions.com/

**Comment by CurePindal** [comment]
Well, then I need to suggest to either use a simple zero for cases with no IP from conversion or remove the default from the checks for associated accounts. 

Because its a bit of a problem if you lookup those users and it spams you over 6000 names into the console/chat, right? =)

@frdmn: Thanks for the link. Very helpful.

**Comment by confuser** [comment]
I have already stated the solution to this problem in my first comment on this issue.

**Comment by CurePindal** [comment]
Dang, now I got it! Sorry, I misunderstood that post as suggestion for "pre-conversion". Non-native english glitch.
