### ISSUE TITLE
Conversion issues - Users lost?

### ISSUE THREAD

**Issue by CurePindal** [confuser/Ban-Management#134]
Hello!

After a conversion test with build 33 our database shrunk from 7300 bans to 6005. A few (~180 users) have been logged as "failed to lookup" but where is the rest?

**Comment by confuser** [comment]
Check your logs as to who failed the lookup. The conversion process will output any that failed. Without the UUID, it can't convert their ban, which is why it's missing.

**Comment by CurePindal** [comment]
The conversion of the different table logged ~250 users not being able to be looked up. (not checked for duplicates).
So theres still over 1000 missing that arent logged. Any clue?

**Comment by confuser** [comment]
Check your logs. Like I said, the conversion process is rather verbose about what it's doing.

**Comment by CurePindal** [comment]
Sorry, but as i said - the users arent logged, nor is there any issue/error that seems to be related to this. Only errors are from trying to convert tables that dont exist. But that also gives no clue why the list of bans is still 1000 entries shorter.

**Comment by confuser** [comment]
You did convert from a v4 database correct?

If it complained about missing tables, then that explains a lot of your problems.

**Comment by frdmn** [comment]
@CurePindal care to show us your server.log that contains the conversion logs?

**Comment by CurePindal** [comment]
Of course. Database was established the startup before, so this is the startup for the conversion only. Startup, conversion, shutdown.

http://pastebin.com/G2F58akU

**Comment by confuser** [comment]
In #133 you stated you tried to convert from v1.6.4. That is incredibly out of date and isn't supported by the converter. It expects your data to be in v4 format.

Update to v1.8, this will create the mute tables.
Update to v1.9, this will create the player ip table.
Update to v2.5, this will create the warning table.
Update to v5 and re-run the conversion.

From your logs, it looks like a lot of your player look ups failed.

I would recommend running the conversion process via a different ip address (i.e. locally and then upload the dump) to your server in case your ip is temporarily blocked by Mojang.

**Comment by confuser** [comment]
Ensure you make backups before doing any of this.

**Comment by CurePindal** [comment]
Could bite my butt that I forgot to give that info. Sorry.
I will follow the update path as you stated in a few hours and report back.

I assume theres no way after the conversion to let BM recheck those UUID lookups that Mojang might have rejected? Does BM re-check the old database after the conversion process if its still enabled in the config?

**Comment by confuser** [comment]
It will re-check the old database if it is still enabled in the config.

However it'll attempt to re-ban the players, which may result in some errors in your console, i.e. stack traces and many 'ban creation failed' messages.

I'm going to leave this issue open until you've solved your problem, and I'm also leaving it open until the conversion process checks to see if the player is not already banned before attempting to create the ban.

**Comment by confuser** [comment]
Latest build checks for bans/mutes before attempting to insert them in the conversion process.

**Comment by confuser** [comment]
@CurePindal have you solved the problem? If not, I'll re-open.

**Comment by CurePindal** [comment]
Sorry, this took longer than expected.

Ive updated the databases to 1.8 -> 1.9 -> 2.5 and now used v5 build 58 on it. Over 700 names havent been converted (some of them are just typos/wrong names).

log: http://pastebin.com/413pVkYV


Running it again over the database v5#33 created no of new bans have been added to it. Its kind of stuck at 6005 bans total (out of 7335).

log: http://pastebin.com/QPK4Vd1w

**Comment by CurePindal** [comment]
Hello?

**Comment by confuser** [comment]
Try the latest developer build. Any bans with typos or players that don't actually exist will fail, which is the correct behaviour.

**Comment by CurePindal** [comment]
I could verify that build 66 successfully converted the latest bans.

So far I couldnt verify a valid username among those ~180 usernames that failed the latest UUID lookup. I hoped that I remembered one of those old bans. But no luck so far.
This is also the difference between the datasets of the old and the new database. 

So from here I have to assume that the conversion was successfully completed with build 66.
