### ISSUE TITLE
Bminfo requiring OP

### ISSUE THREAD

**Issue by Kakifrucht** [confuser/Ban-Management#137]
On build no 40 /bminfo requiers OP status to display a result. If you only have the permission to the command, you won't get a response and no error neither.

**Comment by confuser** [comment]
```
Refactored /bminfo to use permissions for different information
- bm.command.bminfo.playerstats
- bm.command.bminfo.ipstats
- bm.command.bminfo.connection
- bm.command.bminfo.alts
```

I'll document the changes on the uuid update guide on BukkitDev

Leaving this open for the time being in case others have this issue.

**Comment by Kakifrucht** [comment]
Thanks, this is actually a very nice addition!

**Comment by confuser** [comment]
UUID Update page updated.
