### ISSUE TITLE
staff banning staff

### ISSUE THREAD

**Issue by 151baccardi** [confuser/Ban-Management#138]
I'm running V5 latest stable build from 2 days ago... Version 40

Players with these nodes are able to be banned anyways. Groupmanager/Superperms
 - bm.exempt.tempban
 - bm.exempt.banip
 - bm.exempt.mute
 - bm.exempt.tempmute
 - bm.exempt.kick
Nothing works.

Someone posted on bukkit.dev that permissions changed from 
bm.ban  to bm.command.ban
This at least helped me to get banmanager to even perform bans... :(

The rest of the permissions for v4 do not work like bm.exempt.[type]
 
A complete list of new permission for Version 5 would help tremendously since guessing perms is for lunatiks

Thanks

.

**Comment by confuser** [comment]
Exemptions aren't yet in v5 (plugin was rewritten from scratch)

I'll try and get this fixed for you tonight if I get time
