### ISSUE TITLE
Use mod_rewrite to tidy URLs

### ISSUE THREAD

**Issue by davidxd33** [confuser/Ban-Management#84]
This is an enchancment that I will get done [sometime] in the future unless somebody does it before me. 

Give the option to enable mod_rewrite in settings.php then have the file dynamically generated with the proper rewrites. This is highly recommended, even for the original one parked at http//frostcast.net/banmanagement which I expected to already have it.

**Comment by confuser** [comment]
Closing as the web interface is no longer in this repo
