### ISSUE TITLE
Searching not working correctly in web interface

### ISSUE THREAD

**Issue by PhanaticD** [confuser/Ban-Management#87]
I am using the latest version on github as of this post

I search for "dinotech1" but nothing shows up. Even though he is currently banned and has a paste ban record. 

http://gyazo.com/d3cc97230cf32a80f4407033a52b2a37.png
http://gyazo.com/2bb72dcf60f1b1a96c64424a7ab0e46f.png

link to search: http://phanaticmc.com/banmanagement/index.php?player=dinotech1&server=0&action=searchplayer

however, a direct link works: http://phanaticmc.com/banmanagement/index.php?action=viewplayer&player=dinotech1&server=0

**Comment by confuser** [comment]
Closing as the web interface is no longer in this repo.

**Comment by frdmn** [comment]
@PhanaticD If you still have issues, please reopen an issue in this repository instead: 

https://github.com/yeahwhat-mc/BanManager-WebUI
